import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import type { ApiErrorBody, WorkoutDto } from "@forge/shared-contracts";
import "./test-ui.css";
const localDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Ho_Chi_Minh",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const key=()=>crypto.randomUUID();
async function api<T>(url:string,init?:RequestInit):Promise<T>{ const r=await fetch(url,{...init,headers:{"content-type":"application/json",...(init?.headers??{})}}); const body=await r.json(); if(!r.ok)throw Object.assign(new Error((body as ApiErrorBody).error?.message??"Request failed"),{body,status:r.status}); return body as T; }
function App(){
 const [workout,setWorkout]=useState<WorkoutDto|null>(null); const [status,setStatus]=useState("Loading canonical workout…"); const [loadKg,setLoadKg]=useState("80"); const [reps,setReps]=useState("8"); const [pending,setPending]=useState(false); const [retryAction,setRetryAction]=useState<null|(()=>Promise<{workout:WorkoutDto}>)>(null);
 const refresh=async()=>{setStatus("Loading canonical workout…");try{const active=await api<{workout:WorkoutDto|null}>("/api/workouts/active"); if(active.workout){setWorkout(active.workout);setStatus("Canonical active workout loaded.");return;} const today=await api<{workout:WorkoutDto|null}>(`/api/today?date=${localDate()}`);setWorkout(today.workout);setStatus(today.workout?"Today's canonical workout loaded.":"No workout seeded for today.");}catch(e){setStatus(`Load failed: ${(e as Error).message}`)}};
 useEffect(()=>{void refresh()},[]);
 const mutate=async(fn:()=>Promise<{workout:WorkoutDto}>,label:string)=>{setPending(true);setRetryAction(null);setStatus(`${label} pending…`);try{const r=await fn();setWorkout(r.workout);setStatus(`${label} confirmed.`)}catch(e:any){const current=e.body?.error?.current;if(current)setWorkout(current);if(e.status!==409)setRetryAction(()=>fn);setStatus(`${label} failed: ${e.message}${e.status===409?" Canonical state reloaded from conflict response.":" Retry will reuse the same idempotency key."}`)}finally{setPending(false)}};
 if(!workout)return <main><h1>FORGE V2 — Test UI</h1><p role="status">{status}</p><button onClick={()=>void refresh()}>Retry</button></main>;
 const set=workout.exercises[0]?.sets[0];
 return <main><header><p className="badge">EXPERIMENTAL TEST UI</p><h1>{workout.title}</h1><p>{workout.workoutDate} · {workout.state} · version {workout.version}</p></header><p role="status" aria-live="polite">{status}</p>
 {workout.state==="planned"&&<button disabled={pending} onClick={()=>{const idempotencyKey=key();void mutate(()=>api(`/api/workouts/${workout.id}/start`,{method:"POST",body:JSON.stringify({expectedVersion:workout.version,idempotencyKey})}),"Start workout")}}>Start workout</button>}
 {workout.state==="active"&&set&&<section><h2>{workout.exercises[0]?.exerciseName}</h2><p>Set 1 · {set.state}</p>{set.state==="pending"?<><label>Load (kg)<input inputMode="decimal" value={loadKg} onChange={e=>setLoadKg(e.target.value)}/></label><label>Reps<input inputMode="numeric" value={reps} onChange={e=>setReps(e.target.value)}/></label><button disabled={pending} onClick={()=>{const idempotencyKey=key();void mutate(()=>api(`/api/workouts/${workout.id}/sets/${set.id}/complete`,{method:"POST",body:JSON.stringify({expectedVersion:workout.version,idempotencyKey,loadGrams:Math.round(Number(loadKg)*1000),reps:Number(reps)})}),"Complete set")}}>Complete set</button></>:<p>Recorded: {(set.loadGrams??0)/1000} kg × {set.reps}</p>}<button disabled={pending||set.state!=="completed"} onClick={()=>{const idempotencyKey=key();void mutate(()=>api(`/api/workouts/${workout.id}/finish`,{method:"POST",body:JSON.stringify({expectedVersion:workout.version,idempotencyKey})}),"Finish workout")}}>Finish workout</button></section>}
 {workout.state==="completed"&&<section><h2>Completed result</h2><p>{workout.exercises[0]?.exerciseName}: {((set?.loadGrams??0)/1000)} kg × {set?.reps}</p></section>}
 {retryAction&&<button disabled={pending} onClick={()=>void mutate(retryAction,"Retry mutation")}>Retry last mutation</button>}<button className="secondary" disabled={pending} onClick={()=>void refresh()}>Reload canonical state</button></main>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
